/* TODO vraag 1 */

DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS(
    NAME VARCHAR(255),
    AGE INT,
    EMAIL VARCHAR(255) PRIMARY KEY,
    /* TODO Address als column toevoegen */
    ADDRESS VARCHAR(255)
);

/* TODO vraag 2, zelf toe te voegen */
/* TODO op basis van soort relatie, SPORT table foreign key naar EVENT of tussentabel EVENT_SPORT */

DROP TABLE IF EXISTS EVENT;
DROP TABLE IF EXISTS SPORT;
DROP TABLE IF EXISTS EVENT_SPORT;

CREATE TABLE EVENT(
    ID LONG AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255),
    START_DATE DATE,
    END_DATE DATE
);

CREATE TABLE SPORT(
    ID LONG AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255),
    NUM_OF_PLAYERS INT,
    TEAM_SPORT BOOLEAN
);

CREATE TABLE EVENT_SPORT(
    EVENT_ID LONG,
    SPORT_ID LONG,
    PRIMARY KEY (EVENT_ID, SPORT_ID),
    FOREIGN KEY (EVENT_ID) REFERENCES EVENT(ID),
    FOREIGN KEY (SPORT_ID) REFERENCES SPORT(ID)
)