DROP TABLE IF EXISTS EVENT_SPORT;

DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS(
    NAME VARCHAR(255),
    AGE INT,
    EMAIL VARCHAR(255) PRIMARY KEY,
    ADDRESS VARCHAR(255)
);

DROP TABLE IF EXISTS EVENT;

    CREATE TABLE EVENT(
    ID LONG AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255),
    START_DATE DATE,
    END_DATE DATE
);

DROP TABLE IF EXISTS SPORT;

CREATE TABLE SPORT(
    ID LONG AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255),
    NUM_OF_PLAYERS INT,
    TEAM_SPORT BOOLEAN
);

CREATE TABLE EVENT_SPORT(
    EVENT_ID LONG,
    SPORT_ID LONG,
    PRIMARY KEY (EVENT_ID, SPORT_ID),
    FOREIGN KEY (EVENT_ID) REFERENCES EVENT(ID),
    FOREIGN KEY (SPORT_ID) REFERENCES SPORT(ID)
)

